run:
  # include test files or not, default is true
  tests: false

linters:
  disable-all: true
  enable:
    - asciicheck # Simple linter to check that your code does not contain non-ASCII identifiers.
    - deadcode # Finds unused code.
    - errcheck # Errcheck is a program for checking for unchecked errors in go programs.
    - bodyclose # Checks whether HTTP response body is closed successfully.
    - misspell # Finds commonly misspelled English words in comments.
    - govet # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string.
    - unconvert # Remove unnecessary type conversions.
    - unused # Checks Go code for unused constants, variables, functions and types.
    - unparam # Reports unused function parameters
    - varcheck # Finds unused global variables and constants.
    - typecheck # Like the front-end of a Go compiler, parses and type-checks Go code.
    - whitespace # Tool for detection of leading and trailing whitespace.
    - stylecheck # Stylecheck is a replacement for golint.
    - structcheck # Finds unused struct fields.
    - scopelint # Scopelint checks for unpinned variables in go programs.
    - gochecknoinits # Checks that no init functions are present in Go code.
    - goconst # Finds repeated strings that could be replaced by a constant.
    - gocritic # The most opinionated Go source code linter.
    - godot # Check if comments end in a period.
    - gofmt # Gofmt checks whether code was gofmt-ed.
    - goimports # Goimports does everything that gofmt does. Additionally it checks unused imports.
    - golint # Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes
    - gosec # Inspects source code for security problems.
    - gosimple # Linter for Go source code that specializes in simplifying a code.
    - ineffassign # Detects when assignments to existing variables are not used.
    - interfacer # Linter that suggests narrower interface types.
    - maligned # Tool to detect Go structs that would take less memory if their fields were sorted.
    - prealloc # Finds slice declarations that could potentially be preallocated.
    - staticcheck # Staticcheck is a go vet on steroids, applying a ton of static analysis checks.
    - depguard # Go linter that checks if package imports are in a list of acceptable packages.
    - dupl # Tool for code clone detection.
    - nakedret # Finds naked returns in functions greater than a specified function length.
    - gocognit # Computes and checks the cognitive complexity of functions.
    - gocyclo # Computes and checks the cyclomatic complexity of functions.